---
- name: "install httpd software"
  package:
      name: "httpd"
      state: present
- name: "configure httpd service"
  copy:
      src: "index.html"
      dest: "/var/www/html"
  notify: webconfig
